/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.opass.kiosk;

import com.jcraft.jsch.ChannelExec;
import com.jcraft.jsch.JSch;
import com.jcraft.jsch.Session;
import java.awt.event.ItemEvent;
import java.io.BufferedReader;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import redis.clients.jedis.Jedis;

/**
 *
 * @author Prasojo
 */
public class DialogServer extends javax.swing.JDialog {

    String vPass = "";
    Jedis jedis;
    private static QueuePropertyValues qp;
    private static Properties prop;
    private Kiosk parent;

    /**
     * Creates new form DialogServer
     */
    public DialogServer(java.awt.Frame parent, boolean modal, Jedis jedis, Kiosk ksk) {
        super(parent, modal);
        this.parent = ksk;
        this.jedis = jedis;
        initComponents();
        pnlSettings.setVisible(false);
        jButton9.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSatu = new javax.swing.JButton();
        btnDua = new javax.swing.JButton();
        btnTiga = new javax.swing.JButton();
        btnEmpat = new javax.swing.JButton();
        btnLima = new javax.swing.JButton();
        btnEnam = new javax.swing.JButton();
        btnTujuh = new javax.swing.JButton();
        btnDelapan = new javax.swing.JButton();
        btnSembila = new javax.swing.JButton();
        btnNol = new javax.swing.JButton();
        txtPass = new javax.swing.JPasswordField();
        btnClose = new javax.swing.JButton();
        btnEnter = new javax.swing.JButton();
        pnlSettings = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlReset = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btnAktifNpwp = new javax.swing.JCheckBox();
        btnAktifLain = new javax.swing.JCheckBox();
        btnAktifSpt = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        oprJam = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        oprMenit = new javax.swing.JSpinner();
        btnOpr = new javax.swing.JButton();
        txtOpr = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnSatu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSatu.setText("1");
        btnSatu.setPreferredSize(new java.awt.Dimension(59, 23));
        btnSatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSatuActionPerformed(evt);
            }
        });

        btnDua.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDua.setText("2");
        btnDua.setPreferredSize(new java.awt.Dimension(59, 23));
        btnDua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDuaActionPerformed(evt);
            }
        });

        btnTiga.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTiga.setText("3");
        btnTiga.setPreferredSize(new java.awt.Dimension(59, 23));
        btnTiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTigaActionPerformed(evt);
            }
        });

        btnEmpat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEmpat.setText("4");
        btnEmpat.setPreferredSize(new java.awt.Dimension(59, 23));
        btnEmpat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpatActionPerformed(evt);
            }
        });

        btnLima.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLima.setText("5");
        btnLima.setPreferredSize(new java.awt.Dimension(59, 23));
        btnLima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimaActionPerformed(evt);
            }
        });

        btnEnam.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEnam.setText("6");
        btnEnam.setPreferredSize(new java.awt.Dimension(59, 23));
        btnEnam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnamActionPerformed(evt);
            }
        });

        btnTujuh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTujuh.setText("7");
        btnTujuh.setPreferredSize(new java.awt.Dimension(59, 23));
        btnTujuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTujuhActionPerformed(evt);
            }
        });

        btnDelapan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDelapan.setText("8");
        btnDelapan.setPreferredSize(new java.awt.Dimension(59, 23));
        btnDelapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelapanActionPerformed(evt);
            }
        });

        btnSembila.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSembila.setText("9");
        btnSembila.setPreferredSize(new java.awt.Dimension(59, 23));
        btnSembila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSembilaActionPerformed(evt);
            }
        });

        btnNol.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnNol.setText("0");
        btnNol.setPreferredSize(new java.awt.Dimension(59, 23));
        btnNol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNolActionPerformed(evt);
            }
        });

        txtPass.setFocusable(false);

        btnClose.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnClose.setText("<");
        btnClose.setPreferredSize(new java.awt.Dimension(59, 23));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnEnter.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEnter.setText("En");
        btnEnter.setPreferredSize(new java.awt.Dimension(59, 23));
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/opass/kiosk/image/stop_32.png"))); // NOI18N
        jButton5.setText("Start Server");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(500, 365));

        pnlReset.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/opass/kiosk/image/stop_mac.png"))); // NOI18N
        jButton7.setText("Reset SPT");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/opass/kiosk/image/stop_mac.png"))); // NOI18N
        jButton4.setText("Reset NPWP");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/opass/kiosk/image/stop_mac.png"))); // NOI18N
        jButton6.setText("Reset LAIN");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        btnAktifNpwp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAktifNpwp.setSelected(true);
        btnAktifNpwp.setText("NPWP AKTIF");
        btnAktifNpwp.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnAktifNpwpItemStateChanged(evt);
            }
        });
        btnAktifNpwp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAktifNpwpActionPerformed(evt);
            }
        });

        btnAktifLain.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAktifLain.setSelected(true);
        btnAktifLain.setText("LAIN-LAIN AKTIF");
        btnAktifLain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAktifLainActionPerformed(evt);
            }
        });

        btnAktifSpt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAktifSpt.setSelected(true);
        btnAktifSpt.setText("SPPT AKTIF");
        btnAktifSpt.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnAktifSptItemStateChanged(evt);
            }
        });
        btnAktifSpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAktifSptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlResetLayout = new javax.swing.GroupLayout(pnlReset);
        pnlReset.setLayout(pnlResetLayout);
        pnlResetLayout.setHorizontalGroup(
            pnlResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAktifNpwp))
                .addGap(13, 13, 13)
                .addGroup(pnlResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAktifLain))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAktifSpt)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        pnlResetLayout.setVerticalGroup(
            pnlResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResetLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(pnlResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAktifNpwp)
                    .addComponent(btnAktifLain)
                    .addComponent(btnAktifSpt))
                .addGap(31, 31, 31))
        );

        jTabbedPane1.addTab("Reset", pnlReset);

        jLabel1.setText("JAM :");

        oprJam.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        oprJam.setMinimumSize(new java.awt.Dimension(64, 48));
        oprJam.setPreferredSize(new java.awt.Dimension(60, 50));

        jLabel2.setText("MENIT :");

        oprMenit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        btnOpr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/opass/kiosk/image/clock_32.png"))); // NOI18N
        btnOpr.setText("SET OPR");
        btnOpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOprActionPerformed(evt);
            }
        });

        jLabel5.setText("Message :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(oprJam, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel2)
                        .addGap(38, 38, 38)
                        .addComponent(oprMenit, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtOpr))
                .addGap(18, 18, 18)
                .addComponent(btnOpr, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnOpr, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(oprMenit, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(oprJam, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(11, 11, 11))
                                .addComponent(txtOpr))))
                    .addComponent(jLabel1))
                .addGap(157, 157, 157))
        );

        jTabbedPane1.addTab("Operasional", jPanel3);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/opass/kiosk/image/monitor_32.png"))); // NOI18N
        jButton8.setText("Restart  LCD");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/opass/kiosk/image/monitor_32.png"))); // NOI18N
        jButton10.setText("Restart Wait");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/opass/kiosk/image/delete_32.png"))); // NOI18N
        jButton9.setText("Shutdown LCD");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSettingsLayout = new javax.swing.GroupLayout(pnlSettings);
        pnlSettings.setLayout(pnlSettingsLayout);
        pnlSettingsLayout.setHorizontalGroup(
            pnlSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSettingsLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 643, Short.MAX_VALUE)
                    .addGroup(pnlSettingsLayout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton8)
                        .addGap(2, 2, 2)
                        .addComponent(jButton9)
                        .addContainerGap())))
        );
        pnlSettingsLayout.setVerticalGroup(
            pnlSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSettingsLayout.createSequentialGroup()
                        .addGroup(pnlSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13))
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtPass)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnTujuh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnDelapan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnSembila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnNol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnEmpat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnLima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnEnam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnSatu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnDua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnTiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSettings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSatu, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                            .addComponent(btnDua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTiga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEmpat, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                            .addComponent(btnLima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEnam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTujuh, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                            .addComponent(btnDelapan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSembila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNol, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pnlSettings, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSatuActionPerformed
        conPass(btnSatu.getText());
    }//GEN-LAST:event_btnSatuActionPerformed

    private void btnDuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuaActionPerformed
        conPass(btnDua.getText());         // TODO add your handling code here:
    }//GEN-LAST:event_btnDuaActionPerformed

    private void btnTigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTigaActionPerformed
        conPass(btnTiga.getText());
    }//GEN-LAST:event_btnTigaActionPerformed

    private void btnEmpatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpatActionPerformed
        conPass(btnEmpat.getText());
    }//GEN-LAST:event_btnEmpatActionPerformed

    private void btnLimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimaActionPerformed
        conPass(btnLima.getText());
    }//GEN-LAST:event_btnLimaActionPerformed

    private void btnEnamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnamActionPerformed
        conPass(btnEnam.getText());
    }//GEN-LAST:event_btnEnamActionPerformed

    private void btnTujuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTujuhActionPerformed
        conPass(btnTujuh.getText());
    }//GEN-LAST:event_btnTujuhActionPerformed

    private void btnDelapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelapanActionPerformed
        conPass(btnDelapan.getText());
    }//GEN-LAST:event_btnDelapanActionPerformed

    private void btnSembilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSembilaActionPerformed
        conPass(btnSembila.getText());
    }//GEN-LAST:event_btnSembilaActionPerformed

    private void btnNolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNolActionPerformed
        conPass(btnNol.getText());
    }//GEN-LAST:event_btnNolActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        System.out.println(vPass);
        if (vPass.equals("13795")) {
            jedis.set("panngilno", "0");
            pnlSettings.setVisible(true);
            btnSatu.setEnabled(false);
            btnDua.setEnabled(false);
            btnTiga.setEnabled(false);
            btnEmpat.setEnabled(false);
            btnLima.setEnabled(false);
            btnEnam.setEnabled(false);
            btnTujuh.setEnabled(false);
            btnDelapan.setEnabled(false);
            btnSembila.setEnabled(false);
            btnNol.setEnabled(false);
            btnEnter.setEnabled(false);
        } else {
            vPass = "";
            txtPass.setText(vPass);
            JOptionPane.showMessageDialog(rootPane, "Access Denied!");
        }
    }//GEN-LAST:event_btnEnterActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            //Process str = Runtime.getRuntime().exec("/usr/bin/nodejs server.sh");
            Process str = Runtime.getRuntime().exec("/bin/sh server.sh");
            System.out.println(str.getOutputStream().toString());
            JOptionPane.showMessageDialog(this, "Server On, Success!");
        } catch (IOException ex) {
            Logger.getLogger(DialogServer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Reset No Antrian NPWP ?", "Confirm",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {

            jedis.set("loket01_in", "0");
            //jedis.set("loket01_in", "500");

            jedis.set("loket01_status", "0");

            jedis.set("loket01_no", "0");

            jedis.ltrim("q_npwp", 1, 0);
            jedis.ltrim("q_layannpwp", 1, 0);

            jedis.set("countnpwp", "0");

            jedis.set("totalnpwp", "0");

            //jedis.set("countlain", "0");
            // jedis.set("totalnpwp", "0");
            jedis.set("sisanpwp", "0");

            jedis.set("loket01_layan", "0");

            jedis.set("loket01_sts_no", "0");

            //jedis.set("counter_npwp", "500");
            jedis.set("counter_npwp", "0");

            jedis.set("rest_npwp", "1");
            //jedis.set("counter_lainlain", "750");

            JOptionPane.showMessageDialog(this, "Reset No Antrian NPWP, Success!");
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Reset No Antrian LAIN - LAIN ?", "Confirm",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
            //jedis.set("loket02_in", "750");
            jedis.set("loket02_in", "0");
            jedis.set("rest_lain", "1");
            jedis.set("loket02_status", "0");
            jedis.set("loket02_no", "0");
            jedis.ltrim("q_lain", 1, 0);
            jedis.ltrim("q_layanlain", 1, 0);
            jedis.set("countlain", "0");
            jedis.set("totallain", "0");
            jedis.set("sisalain", "0");
            jedis.set("loket02_layan", "0");
            jedis.set("loket02_sts_no", "0");
            //jedis.set("counter_lainlain", "750");
            jedis.set("counter_lainlain", "0");
            JOptionPane.showMessageDialog(this, "Reset No Antrian LAIN-LAIN, Success!");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Reset No Antrian SPT ?", "Confirm",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
            jedis.set("loket03_in", "0");
            jedis.set("loket04_in", "0");
            jedis.set("loket05_in", "0");
            jedis.set("loket06_in", "0");

            jedis.set("loket03_status", "0");
            jedis.set("loket04_status", "0");
            jedis.set("loket05_status", "0");
            jedis.set("loket06_status", "0");

            jedis.set("loket03_no", "0");
            jedis.set("loket04_no", "0");
            jedis.set("loket05_no", "0");
            jedis.set("loket06_no", "0");

            jedis.ltrim("q_sppt", 1, 0);
            jedis.ltrim("q_layansppt_loket03", 1, 0);
            jedis.ltrim("q_layansppt_loket04", 1, 0);
            jedis.ltrim("q_layansppt_loket05", 1, 0);
            jedis.ltrim("q_layansppt_loket06", 1, 0);
            jedis.set("countsppt", "0");

            jedis.set("totalsppt", "0");
            jedis.set("sisasppt", "0");
            //jedis.set("countsppt", "0");

            jedis.set("loket03_layan", "0");
            jedis.set("loket04_layan", "0");
            jedis.set("loket05_layan", "0");
            jedis.set("loket06_layan", "0");

            jedis.set("loket04_sts_no", "0");
            jedis.set("loket03_sts_no", "0");
            jedis.set("loket05_sts_no", "0");

            jedis.set("loket06_sts_no", "0");

            jedis.set("counter_sppt", "0");

            JOptionPane.showMessageDialog(this, "Reset No Antrian SPT, Success!");

        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnOprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOprActionPerformed

        Properties prop2 = new Properties();
        OutputStream output = null;

        try {

            output = new FileOutputStream("config.properties");

            // set the properties value
            prop2.setProperty("JAM_OPR", String.valueOf(oprJam.getValue()));
            prop2.setProperty("MENIT_OPR", String.valueOf(oprMenit.getValue()));
            prop2.setProperty("PESAN_OPR", txtOpr.getText());
            prop2.setProperty("JEDIS_SERVER", "192.168.99.1");
            prop2.setProperty("FRONT_SERVER", "192.168.99.1");
            this.parent.setJAM_OPR(String.valueOf(oprJam.getValue()));
            this.parent.setMENIT_OPR(String.valueOf(oprMenit.getValue()));
            this.parent.setPESAN_OPR(String.valueOf(txtOpr.getText()));
            // save properties to project root folder
            prop2.store(output, null);
            JOptionPane.showMessageDialog(this, "Set Jam Operasional Berhasil...");

        } catch (IOException io) {
        } finally {
            if (output != null) {
                try {
                    output.close();
                } catch (IOException e) {
                }
            }

        }
    }//GEN-LAST:event_btnOprActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            qp = new QueuePropertyValues();
            prop = new Properties(qp.getProperties());
            oprJam.setValue(Integer.parseInt(prop.getProperty("JAM_OPR")));
            oprMenit.setValue(Integer.parseInt(prop.getProperty("MENIT_OPR")));
            txtOpr.setText(prop.getProperty("PESAN_OPR"));
            qp.closeProperties();
        } catch (IOException ex) {
            Logger.getLogger(DialogServer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        int response = JOptionPane.showConfirmDialog(this, "Reset Monitor LCD Antrian ?", "Confirm",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
            try {
                JSch jsch = new JSch();

                //create SSH connection
                String host = "192.168.99.201";
                String user = "pi";
                String password = "pleased3h";

                Session session = jsch.getSession(user, host, 22);
                session.setPassword(password);
                session.setConfig("StrictHostKeyChecking", "no");
                session.connect();

                ChannelExec channel = (ChannelExec) session.openChannel("exec");
                BufferedReader in = new BufferedReader(new InputStreamReader(channel.getInputStream()));

                channel.setCommand("sudo shutdown -r now"); //could be "pwd;" or "sudo shutdown -h now"
                channel.connect();

                String msg = null;
                String wholemessage = "";

                while ((msg = in.readLine()) != null) {
                    wholemessage += msg + "\n";

                }

                Thread.sleep(8000);

                channel.disconnect();
                session.disconnect();
                JOptionPane.showMessageDialog(this, "LCD Monitor Restarted...");
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btnAktifNpwpItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnAktifNpwpItemStateChanged


    }//GEN-LAST:event_btnAktifNpwpItemStateChanged

    private void btnAktifNpwpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAktifNpwpActionPerformed
        if (btnAktifNpwp.isSelected()) {
            this.parent.getBtnA().setVisible(true);
            btnAktifNpwp.setText("NPWP AKTIF");
        } else {//checkbox has been deselected
            this.parent.getBtnA().setVisible(false);
            btnAktifNpwp.setText("NPWP NON AKTIF");

        }
    }//GEN-LAST:event_btnAktifNpwpActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        jedis.set("panngilno", "0");
        JOptionPane.showMessageDialog(this, "Reset Panggilan ( WAIT ) Restarted!");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Shutdown Monitor LCD Antrian ?", "Confirm",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
            try {
                JSch jsch = new JSch();

                //create SSH connection
                String host = "192.168.99.201";
                String user = "pi";
                String password = "pleased3h";

                Session session = jsch.getSession(user, host, 22);
                session.setPassword(password);
                session.setConfig("StrictHostKeyChecking", "no");
                session.connect();

                ChannelExec channel = (ChannelExec) session.openChannel("exec");
                BufferedReader in = new BufferedReader(new InputStreamReader(channel.getInputStream()));

                channel.setCommand("sudo shutdown -h now"); //could be "pwd;" or "sudo shutdown -h now"
                channel.connect();

                String msg = null;
                String wholemessage = "";

                while ((msg = in.readLine()) != null) {
                    wholemessage += msg + "\n";

                }

                Thread.sleep(8000);

                channel.disconnect();
                session.disconnect();
                JOptionPane.showMessageDialog(this, "LCD Monitor Shutdown...");
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnAktifLainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAktifLainActionPerformed
        if (btnAktifLain.isSelected()) {
            this.parent.getBtnB().setVisible(true);
            btnAktifLain.setText("LAIN-LAIN AKTIF");
        } else {//checkbox has been deselected
            this.parent.getBtnB().setVisible(false);
            btnAktifLain.setText("LAIN-LAIN NON AKTIF");
        }
    }//GEN-LAST:event_btnAktifLainActionPerformed

    private void btnAktifSptItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnAktifSptItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAktifSptItemStateChanged

    private void btnAktifSptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAktifSptActionPerformed
        if (btnAktifSpt.isSelected()) {
            this.parent.getBtnC().setVisible(true);
            btnAktifSpt.setText("SPPT AKTIF");
        } else {//checkbox has been deselected
            this.parent.getBtnC().setVisible(false);
            btnAktifSpt.setText("SPPT NON AKTIF");

        }
    }//GEN-LAST:event_btnAktifSptActionPerformed

    private void conPass(String nom) {
        vPass = vPass.concat(nom);
        txtPass.setText(txtPass.getText().concat(vPass));
        System.out.println(vPass);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox btnAktifLain;
    private javax.swing.JCheckBox btnAktifNpwp;
    private javax.swing.JCheckBox btnAktifSpt;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelapan;
    private javax.swing.JButton btnDua;
    private javax.swing.JButton btnEmpat;
    private javax.swing.JButton btnEnam;
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btnLima;
    private javax.swing.JButton btnNol;
    private javax.swing.JButton btnOpr;
    private javax.swing.JButton btnSatu;
    private javax.swing.JButton btnSembila;
    private javax.swing.JButton btnTiga;
    private javax.swing.JButton btnTujuh;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JSpinner oprJam;
    private javax.swing.JSpinner oprMenit;
    private javax.swing.JPanel pnlReset;
    private javax.swing.JPanel pnlSettings;
    private javax.swing.JTextField txtOpr;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
